name : media_repository
description : A repository for camera


version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  content_repository:
    path: ../content_repository
  camera: ^0.9.4+19
dev_dependencies:
  flutter_test:
    sdk: flutter